apiVersion: v1
kind: Secret
metadata:
  name: newsapp-secrets
  namespace: newsapp
type: Opaque
stringData:
  POSTGRES_USER: "newsapp"
  POSTGRES_PASSWORD: "tmp-placeholder"
  POSTGRES_DB: "newsapp"
  NEWSDATA_API_KEY: "tmp-placeholder"
  DEV_ADMIN_TOKEN: "tmp-placeholder"
