apiVersion: v1
kind: Service
metadata:
  name: newsapp-api
  namespace: newsapp
spec:
  selector:
    app: newsapp-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsapp-api
  namespace: newsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsapp-api
  template:
    metadata:
      labels:
        app: newsapp-api
    spec:
      containers:
        - name: api
          image: filipjovanovski1/newsapp-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: newsapp-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: newsapp-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: newsapp-secrets
                  key: POSTGRES_DB

            - name: Newsdata__ApiKey
              valueFrom:
                secretKeyRef:
                  name: newsapp-secrets
                  key: NEWSDATA_API_KEY

            - name: Dev__AdminToken
              valueFrom:
                secretKeyRef:
                  name: newsapp-secrets
                  key: DEV_ADMIN_TOKEN

            - name: Dev__DataRoot
              value: "/app/Data"

            # Step B (dev import endpoints)
            - name: Dev__Enabled
              value: "false"

            - name: Database__ApplyMigrationsOnStartup
              value: "true"

            # Build the connection string from the env vars above
            - name: ConnectionStrings__Default
              value: "Host=postgres;Port=5432;Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD);Include Error Detail=true"
