apiVersion: v1
kind: ConfigMap
metadata:
  name: newsapp-config
  namespace: newsapp
data:
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_ENVIRONMENT: "Production"

  Dev__DataRoot: "/app/Data"
  Dev__Enabled: "false"
  Database__ApplyMigrationsOnStartup: "true"
  DiscoveryPipeline__BaseUrl: "http://news-source-discovery:8000"
  DiscoveryPipeline__CallbackBaseUrl: "http://newsapp-api:8080"
  DiscoveryScheduler__Enabled: "true"
  DiscoveryScheduler__DispatchBatchSize: "1"
  DiscoveryScheduler__FeedBatchSize: "500"
  DiscoveryScheduler__PollBatchSize: "100"
